trigger:
- master

pool: 'Hosted Windows 2019 with VS2019'

steps:
- template: writeAppSettings.yml
  parameters:
    projectPath: '.'
    resourceGroupServiceConnection: 'prod-deploy-service-connection'
    keyVaultName: 'benbo-6-23-1-keyvault'
    microsoftAppIdSecretName: 'microsoftAppId'
    microsoftAppPasswordSecretName: 'microsoftAppPassword'
- template: publishAndConfigureLuis.yml
  parameters:
    projectPath: '.'
    resourceGroupServiceConnection: 'prod-deploy-service-connection'
    keyVaultName: 'benbo-6-23-1-keyvault'
    luisResourceName: 'benbo-6-23-1-dev-luis'
    resourceGroupName: 'benbo-6-23-1-dev'
    luisAuthoringKeySecretName: 'luisAuthoringKey'
    luisEndpointKeySecretName: 'luisEndpointKey'
- template: prepareBotDefaultRuntime.yml
  parameters:
    projectPath: '.'
- template: buildAndDeployAppService.yml
  parameters:
    resourceGroupServiceConnection: 'prod-deploy-service-connection'
    appServiceResourceName: 'benbo-6-23-1-dev'